# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_categories', '0004_auto_20150623_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='link'),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='name'),
        ),
    ]
