# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0005_auto_20180619_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='no_url',
            field=models.BooleanField(default=False, verbose_name='no url'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='summary'),
        ),
    ]
