# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-23 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0006_auto_20180619_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytranslation',
            name='landing_page',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='landing page'),
        ),
    ]
